### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by silkstudio** [silkstudio/styled-framework#4]
Here's the roadmap for how the library is planning to progress. This issue will act as a rolling thread to keep track of where things are at.

&nbsp;
## Phase 1 - Initial MVP
- [ ] Create basic working product which allows for use of the librarys functions to pass style props, which are type-checked against css-type.

## Phase 2
- [ ] Add a scale prop to the styleParser function that can be used as the first-port-of-call for emit suggestions.
- [ ] Create a more strictly typed theme based on whether a property can have an object, array or both assigned to it
- [ ] Make a descision on rules for how to parse different types of style values
- [ ] Implement a unitless function to add units to plain numbers _(but only in certain circumstances based on the above)_
- [ ] Implement a test suite to check everything is working

## Phase 3
- [ ] Add intellisense through ts to enable suggestions for props based on theme and scale
- [ ] Add transformers to select props to allow _'power-user'_ syntax _(e.g. gridRow, gridCol, margin, padding, width, height)_
- [ ] Add aliases _(with type support)_ to common props allowing cleaner syntax

&nbsp;
## Longer term
- [ ] Create compose function for improved performance
